import axios from 'axios';
import Head from 'next/head';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import ChronologyPost from '../components/ChronologyPost';
import Posts from '../components/Posts';
import PostsFive from '../components/PostsFive';
import PostsThree from '../components/PostsThree';
import PostsTwo from '../components/PostsTwo';
import { postsData } from '../utils/data';

const articles = ({ data }) => {
  const [posts, setPosts] = useState(data);
  console.log(posts);
  const switchStatus = useSelector((state) => state.switch.status);

  return (
    <div className='container'>
      <Head>
        <title>Истории</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {switchStatus ? (
        <main className=' main chronology-container'>
          <div className='chronology-grid '>
            <ChronologyPost posts={posts} start={0} end={6} />
          </div>
        </main>
      ) : (
        <main className='main second-grid '>
          <Posts variantPost={3} posts={posts} start={5} end={8} />
          <Posts variantPost={2} posts={posts} start={3} end={5} />
          <Posts variantPost={3} posts={posts} start={7} end={10} />
          <Posts variantPost={2} posts={posts} start={0} end={2} />
          <Posts variantPost={3} posts={posts} start={11} end={14} />
          <Posts variantPost={2} posts={posts} start={6} end={8} />
        </main>
      )}
    </div>
  );
};

export default articles;

export async function getServerSideProps({ params }) {
  const res = await axios.get(
    'http://localhost:1337/posts?categories.name=articles'
  );
  const data = res.data;

  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}