import Head from 'next/head';
import { useState } from 'react';
import PostsFive from '../components/PostsFive';
import PostsThree from '../components/PostsThree';
import PostsTwo from '../components/PostsTwo';
import { postsData } from '../utils/data';

const shapito = () => {
     const [posts, setPosts] = useState(postsData);

    return (
      <div className='container'>
        <Head>
          <title>Шапито</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className='container main'>
          <div className='shapito-grid'>
            <PostsThree posts={posts} start={2} end={5} />
            <PostsTwo posts={posts} start={0} end={2} />
            <PostsThree posts={posts} start={2} end={6} />
          </div>
          <div className='second-grid'>
            <PostsThree posts={posts} start={2} end={5} />
            <PostsTwo posts={posts} start={0} end={2} />
            <PostsThree posts={posts} start={2} end={5} />
            <PostsTwo posts={posts} start={0} end={2} />
          </div>
        </main>
      </div>
    );
};

export default shapito;