import axios from 'axios';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import ChronologyPost from '../components/ChronologyPost';
import Posts from '../components/Posts';
import PostsThree from '../components/PostsThree';
import PostsTwo from '../components/PostsTwo';


const shapito = ({ data }) => {
  
  const posts = data
     .map((i) => [Math.random(), i])
     .sort()
     .map((i) => i[1]);
  const switchStatus = useSelector((state) => state.switch.status);

  return (
    <div className='container'>
      <Head>
        <title>Шапито</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {switchStatus ? (
        <main className=' main chronology-container'>
          <div className='chronology-grid '>
            <ChronologyPost posts={posts} start={0} end={6} />
          </div>
        </main>
      ) : (
        <main className='container main'>
          <div className='shapito-grid'>
            <Posts variantPost={3} posts={posts} start={2} end={5} />
            <Posts variantPost={2} posts={posts} start={0} end={2} />
            <Posts variantPost={3} posts={posts} start={2} end={6} />
          </div>
          <div className='second-grid'>
            <Posts variantPost={3} posts={posts} start={2} end={5} />
            <Posts variantPost={2} posts={posts} start={0} end={2} />
            <Posts variantPost={3} posts={posts} start={5} end={8} />
            <Posts variantPost={2} posts={posts} start={9} end={11} />
          </div>
        </main>
      )}
    </div>
  );
};

export default shapito;

export async function getServerSideProps({ params }) {
  const res = await axios.get(
    'http://localhost:1337/posts?categories.name=shapito'
  );
  const data = res.data;

  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}